### ISSUE TITLE
casparser.exceptions.CASParseError: Unable to parse investor data

### ISSUE THREAD

**Issue by ajitup73** [codereverser/casparser#55]
while running casparser, it is giving following error:

data = casparser.read_cas_pdf("CAMS_pranshu766.pdf", "pranshu766")
Deprecation: 'getTextPage' removed from class 'Page' after v1.19.0 - use 'get_textpage'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/ajitup/anaconda3/lib/python3.8/site-packages/casparser/parsers/__init__.py", line 33, in read_cas_pdf
    partial_cas_data = cas_pdf_to_text(filename, password)
  File "/home2/ajitup/anaconda3/lib/python3.8/site-packages/casparser/parsers/mupdf.py", line 213, in cas_pdf_to_text
    investor_info = parse_investor_info(page_dict)
  File "/home2/ajitup/anaconda3/lib/python3.8/site-packages/casparser/parsers/mupdf.py", line 145, in parse_investor_info
    raise CASParseError("Unable to parse investor data")
casparser.exceptions.CASParseError: Unable to parse investor data

Please help!

**Comment by codereverser** [comment]
Looks like the investor section of the file is in a different format than expected. Can you please post a screenshot of the investor info section from the pdf file, with all personal info blurred? 

like 
![cams_snap](https://user-images.githubusercontent.com/8553055/145613832-18d95c98-c494-44a0-9d95-5f0ecdb58dfd.png)

**Comment by codereverser** [comment]
closing as there is no response. please feel free to re-open with more info
